### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by ansgarschulte** [herrevilkitten/telnet-rxjs#14]
Hi
is it possible to update the node version to a newer one?

Thx

**Comment by herrevilkitten** [comment]
@ansgarschulte Thanks for the PR.  Getting everything up-to-date took a lot more work than I expected, but it is published now. I just hope it works :)

https://www.npmjs.com/package/telnet-rxjs

**Comment by ansgarschulte** [comment]
thank you!
