### ISSUE TITLE
Need example of sending telnet commands, as well as will/wont/do/dont

### ISSUE THREAD

**Issue by montsamu** [herrevilkitten/telnet-rxjs#8]
This is a wonderful package to use so far, but I am having trouble understanding how to **send** telnet commands, at least when acting as a telnet proxy. I am successfully subscribing to command events and seeing the tuples:

```

const telnetd = Telnet.server(telnet_port);

telnetd.filter((event) => event instanceof Telnet.Event.Connected)
  .subscribe((event) => {
    const client = event.connection;
    client.tclient = Telnet.client(url);

  ...

  client.commands.subscribe((commands) => {
    console.log("command from client:", commands);
    const buf = Buffer.from(commands);
    client.tclient.socket.write(buf);

  ...

    client.tclient.commands.subscribe((commands) => {
      console.log("command from server:", commands);
      const buf = Buffer.from(commands);
      client.socket.write(buf);
    });

```

I do see the commands emitted by the server:

command from server: [ 255, 251, 252 ]

And I am able to send these on to the client, which responds with:

command from client: [ 255, 254, 255 ]

However I'm apparently having a little bit of difficulty at this point sending this command back to the eventual server; it ends up eventually/also showing up as "garbage" message data from the client ("ï¿½") instead of actually going to the server and happening as expected. (In this case, suppressing output/echo during password typing.)

I'm also struggling a bit to do proper will/wont/do/dont/sub negotiations easily; I don't want to have to use an additional decorator (although the telnet-stream package is certainly nice enough!) if I don't need to introduce another dependency.

So, if there is an example of will/wont/do/dont/sub negotiations (even a "window resize" example) that would be very appreciated.

**Comment by herrevilkitten** [comment]
An excellent question.  I'll see what I can do.  I was originally porting some old MUD code to node, so I'll look in there.

**Comment by montsamu** [comment]
Thank you -- I turned on some debugging with my telnet client

telnet> set options
telnet> set termdata

And my telnet process gets:

RCVD WILL 252
SENT DONT 252

What I think is also happening is that the "SENT DONT 252" reply (from my UNIX telnet process) is being interpreted *BOTH* as "data" being received by telnet-rxjs, as well as a "command" being received.

That is:

    client.data.subscribe((data) => {

Is being triggered both on "regular" data, as well as on commands.

**Comment by herrevilkitten** [comment]
There's a bug in `connection.ts`:

```
        if (data[position] === Command.SB) {
            while (position < data.length) {
                telnetCommand.push(data[position++]);
                if (data[position] === Command.SE) {
                    break;
                }
            }
        } else {
            telnetCommand.push(data[position]++);
            telnetCommand.push(data[position]++);
        }
```

For telnet commands that do a subnegotiation (`SB`), it properly increments the cursor position until the very end.  For all other telnet commands, it

1. is not incrementing the position
2. is incrementing the `data`, so you're not even getting the right command anyway

**Comment by montsamu** [comment]
Thanks for following up on that!

**Comment by herrevilkitten** [comment]
Checkout v2.0.4
